name: Setup BC Dev Tools
description: Downloads and extracts BC Development Tools assets to specified folder

inputs:
  version-number:
    description: Specify specific version to download
    required: true
  target-path:
    description: Target path to extract files
    required: false
    default: Microsoft.Dynamics.BusinessCentral.Development.Tools

runs:
  using: composite
  steps:
    - name: Get source for BC Dev Tools
      id: get-bc-devtools
      shell: pwsh
      run: |
        # Retrieve source Uri from Marketplace
        $sourceUri = ${{github.action_path}}/Marketplace.ps1 -Version ${{ inputs.version-number }}
        echo "source-uri=$($sourceUri)" >> $env:GITHUB_OUTPUT

    - name: Download BC DevTools asset
      id: download-bc-devtools-asset
      if: ${{ steps.get-bc-devtools.outputs.source-uri != '' }}
      shell: pwsh
      env:
        ASSET_URI: ${{ steps.get-bc-devtools.outputs.source-uri }}
      run: |
        #  Download BC DevTools asset
        $downloadPath = ${{github.action_path}}/Download-BcDevToolsAsset.ps1 -AssetUri $env:ASSET_URI
        "download-path=$downloadPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8

    - name: Extract BC DevTools asset
      shell: pwsh
      env:
        ARCHIVE_PATH: ${{ steps.download-bc-devtools-asset.outputs.download-path }}
        TARGET_PATH: ${{ inputs.target-path }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        Write-Output "Extracting $env:ARCHIVE_PATH ..."

        & "$env:ACTION_PATH\Extract-RequiredFiles.ps1" -DestinationPath $env:TARGET_PATH -ArchivePath $env:ARCHIVE_PATH -PathInArchive 'extension/bin/Analyzers'
