name: Pull Request Validation

on:
  pull_request:
    branches: [ main, master ]
    paths:
      - 'src/**'
      - '*.sln'
      - '*.props'
      - '*.targets'
      - 'global.json'
      - 'nuget.config'
      - '.github/workflows/**'

permissions:
  contents: read
      
env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build-pack-validate:
    name: Build, Pack and Validate
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET SDKs
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          8.0.x        
        cache: true
        cache-dependency-path: |
          **/*.csproj
          **/packages.lock.json
          nuget.config

    - name: GitVersion - Setup
      uses: gittools/actions/gitversion/setup@v3
      with:
        versionSpec: '5.x'

    - name: GitVersion - Determine
      id: gitversion
      uses: gittools/actions/gitversion/execute@v3
      with:
        useConfigFile: true

    - name: Setup BC DevTools (netstandard2.1)
      id: setup-bc-devtools-netstandard21
      uses: ./.github/actions/setup-bc-devtools
      with:
        version-number: '12.0.875970'
        target-path: 'Microsoft.Dynamics.BusinessCentral.Development.Tools/netstandard2.1'

    - name: Setup BC DevTools (net8.0)
      id: setup-bc-devtools-net80
      uses: ./.github/actions/setup-bc-devtools
      with:
        version-number: '16.0.1463980'
        target-path: 'Microsoft.Dynamics.BusinessCentral.Development.Tools/net8.0'

    - name: Restore
      run: dotnet restore src/RoslynTestKit.sln

    - name: Build
      run: >
        dotnet build src/RoslynTestKit.sln --no-restore --configuration Release
        /p:ContinuousIntegrationBuild=true
        /p:Version=${{ steps.gitversion.outputs.nuGetVersionV2 }}
        /p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemVer }}
        /p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }}

    - name: Pack
      run: >
        dotnet pack src/RoslynTestKit/RoslynTestKit.csproj --configuration Release
        /p:ContinuousIntegrationBuild=true 
        /p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }}
        --output ./packages

    - name: Validate package manifest
      run: |
        dotnet tool install --global dotnet-validate --version 0.0.1-preview.304
        dotnet-validate package local ./packages/*.nupkg

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: nuget-package
        path: ./packages/*.nupkg
        retention-days: 7